// Generated by gencpp from file arm_info/kinemarics.msg
// DO NOT EDIT!


#ifndef ARM_INFO_MESSAGE_KINEMARICS_H
#define ARM_INFO_MESSAGE_KINEMARICS_H

#include <ros/service_traits.h>


#include <arm_info/kinemaricsRequest.h>
#include <arm_info/kinemaricsResponse.h>


namespace arm_info
{

struct kinemarics
{

typedef kinemaricsRequest Request;
typedef kinemaricsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinemarics
} // namespace arm_info


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_info::kinemarics > {
  static const char* value()
  {
    return "d4d7066ccc45dfff67e7b0b528d14e9b";
  }

  static const char* value(const ::arm_info::kinemarics&) { return value(); }
};

template<>
struct DataType< ::arm_info::kinemarics > {
  static const char* value()
  {
    return "arm_info/kinemarics";
  }

  static const char* value(const ::arm_info::kinemarics&) { return value(); }
};


// service_traits::MD5Sum< ::arm_info::kinemaricsRequest> should match
// service_traits::MD5Sum< ::arm_info::kinemarics >
template<>
struct MD5Sum< ::arm_info::kinemaricsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_info::kinemarics >::value();
  }
  static const char* value(const ::arm_info::kinemaricsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_info::kinemaricsRequest> should match
// service_traits::DataType< ::arm_info::kinemarics >
template<>
struct DataType< ::arm_info::kinemaricsRequest>
{
  static const char* value()
  {
    return DataType< ::arm_info::kinemarics >::value();
  }
  static const char* value(const ::arm_info::kinemaricsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_info::kinemaricsResponse> should match
// service_traits::MD5Sum< ::arm_info::kinemarics >
template<>
struct MD5Sum< ::arm_info::kinemaricsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_info::kinemarics >::value();
  }
  static const char* value(const ::arm_info::kinemaricsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_info::kinemaricsResponse> should match
// service_traits::DataType< ::arm_info::kinemarics >
template<>
struct DataType< ::arm_info::kinemaricsResponse>
{
  static const char* value()
  {
    return DataType< ::arm_info::kinemarics >::value();
  }
  static const char* value(const ::arm_info::kinemaricsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_INFO_MESSAGE_KINEMARICS_H
